"""Add created_at to study_logs

Revision ID: 7fb302c9f778
Revises: cecdbc479ad1
Create Date: 2026-03-07 21:36:40.085098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb302c9f778'
down_revision: Union[str, Sequence[str], None] = 'cecdbc479ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('conversations', 'topic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('conversations', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('conversations', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('kanban_boards', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('kanban_boards_owner_id_fkey'), 'kanban_boards', type_='foreignkey')
    op.create_foreign_key(None, 'kanban_boards', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.alter_column('kanban_cards', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('kanban_cards', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('kanban_cards', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('kanban_cards', 'column_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_kanban_cards_title'), table_name='kanban_cards')
    op.drop_constraint(op.f('kanban_cards_column_id_fkey'), 'kanban_cards', type_='foreignkey')
    op.create_foreign_key(None, 'kanban_cards', 'kanban_columns', ['column_id'], ['id'], ondelete='CASCADE')
    op.alter_column('kanban_columns', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('kanban_columns', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('kanban_columns', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_kanban_columns_title'), table_name='kanban_columns')
    op.drop_constraint(op.f('kanban_columns_board_id_fkey'), 'kanban_columns', type_='foreignkey')
    op.create_foreign_key(None, 'kanban_columns', 'kanban_boards', ['board_id'], ['id'], ondelete='CASCADE')
    op.alter_column('study_group_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('study_group_members', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('study_group_members_group_id_fkey'), 'study_group_members', type_='foreignkey')
    op.drop_constraint(op.f('study_group_members_user_id_fkey'), 'study_group_members', type_='foreignkey')
    op.create_foreign_key(None, 'study_group_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'study_group_members', 'study_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.alter_column('study_groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('study_groups', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_study_groups_name'), table_name='study_groups')
    op.create_index(op.f('ix_study_groups_name'), 'study_groups', ['name'], unique=True)
    op.drop_constraint(op.f('study_groups_creator_id_fkey'), 'study_groups', type_='foreignkey')
    op.create_foreign_key(None, 'study_groups', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.add_column('study_logs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('study_logs', 'topic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('study_logs', 'hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('study_logs', 'study_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('study_logs', 'focus_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('study_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('study_logs_user_id_fkey'), 'study_logs', type_='foreignkey')
    op.create_foreign_key(None, 'study_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'total_xp',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'total_xp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'study_logs', type_='foreignkey')
    op.create_foreign_key(op.f('study_logs_user_id_fkey'), 'study_logs', 'users', ['user_id'], ['id'])
    op.alter_column('study_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('study_logs', 'focus_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('study_logs', 'study_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('study_logs', 'hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('study_logs', 'topic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('study_logs', 'created_at')
    op.drop_constraint(None, 'study_groups', type_='foreignkey')
    op.create_foreign_key(op.f('study_groups_creator_id_fkey'), 'study_groups', 'users', ['creator_id'], ['id'])
    op.drop_index(op.f('ix_study_groups_name'), table_name='study_groups')
    op.create_index(op.f('ix_study_groups_name'), 'study_groups', ['name'], unique=False)
    op.alter_column('study_groups', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('study_groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'study_group_members', type_='foreignkey')
    op.drop_constraint(None, 'study_group_members', type_='foreignkey')
    op.create_foreign_key(op.f('study_group_members_user_id_fkey'), 'study_group_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('study_group_members_group_id_fkey'), 'study_group_members', 'study_groups', ['group_id'], ['id'])
    op.alter_column('study_group_members', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('study_group_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'kanban_columns', type_='foreignkey')
    op.create_foreign_key(op.f('kanban_columns_board_id_fkey'), 'kanban_columns', 'kanban_boards', ['board_id'], ['id'])
    op.create_index(op.f('ix_kanban_columns_title'), 'kanban_columns', ['title'], unique=False)
    op.alter_column('kanban_columns', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('kanban_columns', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('kanban_columns', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'kanban_cards', type_='foreignkey')
    op.create_foreign_key(op.f('kanban_cards_column_id_fkey'), 'kanban_cards', 'kanban_columns', ['column_id'], ['id'])
    op.create_index(op.f('ix_kanban_cards_title'), 'kanban_cards', ['title'], unique=False)
    op.alter_column('kanban_cards', 'column_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('kanban_cards', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('kanban_cards', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('kanban_cards', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'kanban_boards', type_='foreignkey')
    op.create_foreign_key(op.f('kanban_boards_owner_id_fkey'), 'kanban_boards', 'users', ['owner_id'], ['id'])
    op.alter_column('kanban_boards', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'])
    op.alter_column('conversations', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('conversations', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('conversations', 'topic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
